In [296]:
#importing the required libraries
import pandas as pd
import matplotlib.pyplot as plt
#reading csv file
df = pd.read_csv("survey_results_public.csv")

In [297]:
df.head()

ResponseId                                         MainBranch  \
0           1                     I am a developer by profession   
1           2             I am a student who is learning to code   
2           3  I am not primarily a developer, but I write co...   
3           4                     I am a developer by profession   
4           5                     I am a developer by profession   

                                          Employment  \
0  Independent contractor, freelancer, or self-em...   
1                                 Student, full-time   
2                                 Student, full-time   
3                                 Employed full-time   
4  Independent contractor, freelancer, or self-em...   

                                             Country US_State UK_Country  \
0                                           Slovakia      NaN        NaN   
1                                        Netherlands      NaN        NaN   
2                                 Russian Federation      NaN        NaN   
3                                            Austria      NaN        NaN   
4  United Kingdom of Great Britain and Northern I...      NaN    England   

                                             EdLevel     Age1stCode  \
0  Secondary school (e.g. American high school, G...  18 - 24 years   
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  11 - 17 years   
2       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  11 - 17 years   
3    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  11 - 17 years   
4    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   5 - 10 years   

                                           LearnCode YearsCode  ...  \
0  Coding Bootcamp;Other online resources (ex: vi...       NaN  ...   
1  Other online resources (ex: videos, blogs, etc...         7  ...   
2  Other online resources (ex: videos, blogs, etc...       NaN  ...   
3                                                NaN       NaN  ...   
4                            Friend or family member        17  ...   

               Age Gender Trans                Sexuality  \
0  25-34 years old    Man    No  Straight / Heterosexual   
1  18-24 years old    Man    No  Straight / Heterosexual   
2  18-24 years old    Man    No        Prefer not to say   
3  35-44 years old    Man    No  Straight / Heterosexual   
4  25-34 years old    Man    No                      NaN   

                      Ethnicity                Accessibility  \
0  White or of European descent            None of the above   
1  White or of European descent            None of the above   
2             Prefer not to say            None of the above   
3  White or of European descent  I am deaf / hard of hearing   
4  White or of European descent            None of the above   

        MentalHealth           SurveyLength                  SurveyEase  \
0  None of the above  Appropriate in length                        Easy   
1  None of the above  Appropriate in length                        Easy   
2  None of the above  Appropriate in length                        Easy   
3                NaN  Appropriate in length  Neither easy nor difficult   
4                NaN  Appropriate in length                        Easy   

  ConvertedCompYearly  
0             62268.0  
1                 NaN  
2                 NaN  
3                 NaN  
4                 NaN  

[5 rows x 48 columns]

In [298]:
df = df[["Country", "EdLevel", "YearsCodePro", "Employment" ,"ConvertedCompYearly"]]
#renaming convertedcomp to salary
df = df.rename({"ConvertedCompYearly": "Salary"}, axis=1)
df.head()

Country  \
0                                           Slovakia   
1                                        Netherlands   
2                                 Russian Federation   
3                                            Austria   
4  United Kingdom of Great Britain and Northern I...   

                                             EdLevel YearsCodePro  \
0  Secondary school (e.g. American high school, G...          NaN   
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)          NaN   
2       Bachelor’s degree (B.A., B.S., B.Eng., etc.)          NaN   
3    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)          NaN   
4    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)           10   

                                          Employment   Salary  
0  Independent contractor, freelancer, or self-em...  62268.0  
1                                 Student, full-time      NaN  
2                                 Student, full-time      NaN  
3                                 Employed full-time      NaN  
4  Independent contractor, freelancer, or self-em...      NaN

In [299]:
df = df[df["Salary"].notnull()]
df.head()

Country                                            EdLevel YearsCodePro  \
0   Slovakia  Secondary school (e.g. American high school, G...          NaN   
9     Sweden    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            4   
11     Spain       Bachelor’s degree (B.A., B.S., B.Eng., etc.)            5   
12   Germany    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)            6   
16    Turkey       Bachelor’s degree (B.A., B.S., B.Eng., etc.)            2   

                                           Employment   Salary  
0   Independent contractor, freelancer, or self-em...  62268.0  
9                                  Employed full-time  51552.0  
11                                 Employed full-time  46482.0  
12                                 Employed full-time  77290.0  
16                                 Employed full-time  17748.0

In [300]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3752 entries, 0 to 6538
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       3752 non-null   object 
 1   EdLevel       3749 non-null   object 
 2   YearsCodePro  3667 non-null   object 
 3   Employment    3752 non-null   object 
 4   Salary        3752 non-null   float64
dtypes: float64(1), object(4)
memory usage: 175.9+ KB


In [301]:
#dropping the empty columns
df = df.dropna()
df.isnull().sum()

Country         0
EdLevel         0
YearsCodePro    0
Employment      0
Salary          0
dtype: int64

In [302]:
#keeping only full time employed employees and dropping the rest
df = df[df["Employment"] == "Employed full-time"]
df = df.drop("Employment", axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3179 entries, 9 to 6538
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       3179 non-null   object 
 1   EdLevel       3179 non-null   object 
 2   YearsCodePro  3179 non-null   object 
 3   Salary        3179 non-null   float64
dtypes: float64(1), object(3)
memory usage: 124.2+ KB


In [303]:
#cleaning the 'country' data 
df['Country'].value_counts()

United States of America                                911
Germany                                                 237
United Kingdom of Great Britain and Northern Ireland    237
India                                                   207
Canada                                                  170
                                                       ... 
Hong Kong (S.A.R.)                                        1
Ethiopia                                                  1
Yemen                                                     1
Bolivia                                                   1
The former Yugoslav Republic of Macedonia                 1
Name: Country, Length: 105, dtype: int64

In [304]:
def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
      #if the number of samples is greater than or equal to the cutoff value we keep the country else combine it into a new category named as 'other'
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map

In [305]:
#executing shorten_categories function with cutoff value 400
country_map = shorten_categories(df.Country.value_counts(), 90)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()

Other                                                   1271
United States of America                                 911
Germany                                                  237
United Kingdom of Great Britain and Northern Ireland     237
India                                                    207
Canada                                                   170
France                                                   146
Name: Country, dtype: int64

In [306]:
#cleaning the 'YearsCodePro' data
df["YearsCodePro"].unique()

array(['4', '5', '6', '2', '18', '21', '16', '10', 'Less than 1 year',
       '15', '3', '1', '12', '8', '17', '14', '7', '26', '34', '11', '25',
       '24', '22', '13', '9', '20', '23', '39', '27', '35', '30', '19',
       '33', '37', '43', '40', '29', '38', '31', '45', '42', '28', '46',
       '32', '36', '47', '44'], dtype=object)

In [307]:
#converting experience into float
def clean_experience(x):
    if x ==  'More than 50 years':
        return 50
    if x == 'Less than 1 year':
        return 0.5
    return float(x)

df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

In [308]:
df["EdLevel"].unique()

array(['Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Some college/university study without earning a degree',
       'Professional degree (JD, MD, etc.)',
       'Other doctoral degree (Ph.D., Ed.D., etc.)', 'Something else',
       'Primary/elementary school', 'Associate degree (A.A., A.S., etc.)',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)'],
      dtype=object)

In [309]:
#combining the categories in education
def clean_education(x):
    if 'Bachelor’s degree' in x:
        return 'Bachelor’s degree'
    if 'Master’s degree' in x:
        return 'Master’s degree'
    if 'Professional degree' in x or 'Other doctoral' in x:
        return 'Post grad'
    return 'Less than a Bachelors'

df['EdLevel'] = df['EdLevel'].apply(clean_education)

In [310]:
df["EdLevel"].unique()

array(['Master’s degree', 'Bachelor’s degree', 'Less than a Bachelors',
       'Post grad'], dtype=object)

In [311]:
#transforming the data as experience is float and country is a string
from sklearn.preprocessing import LabelEncoder
le_education = LabelEncoder()
df['EdLevel'] = le_education.fit_transform(df['EdLevel'])
df["EdLevel"].unique()
#now we have numbers 0,2,1,3 . the label encoder knows which number belongs to which category

array([2, 0, 1, 3])

In [312]:
#doing same for the country
le_country = LabelEncoder()
df['Country'] = le_country.fit_transform(df['Country'])
df["Country"].unique()


array([4, 2, 0, 1, 5, 6, 3])

In [313]:
#starrting training our model splitiing into feature X and label y
X = df.drop("Salary", axis=1)
y = df["Salary"]

In [314]:
#importing linear regression 
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
#fitting X and y
linear_reg.fit(X, y.values)

LinearRegression()

In [315]:
#predicting new values
y_pred = linear_reg.predict(X)

In [316]:
#to check how good the model performs by checking the mean square error
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
#calculating mean squared error based on actual labels y and y_pred
error = np.sqrt(mean_squared_error(y, y_pred))
error

368827.21556724363

In [317]:
#trying the next model
#import decision tree regressor
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
#fit the data
dec_tree_reg.fit(X, y.values)

DecisionTreeRegressor(random_state=0)

In [318]:
#predicting the value
y_pred = dec_tree_reg.predict(X)

In [319]:
#finding mean squared error
error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))

$349,419.74


In [320]:
#trying next model
#importing random forest regressor
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
#fit the data
random_forest_reg.fit(X, y.values)

RandomForestRegressor(random_state=0)

In [321]:
#predict the values
y_pred = random_forest_reg.predict(X)

In [322]:
#finding the error
error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))

$349,998.42


In [323]:
# #trying new grid search cv method
from sklearn.model_selection import GridSearchCV
#defining the set of diffrent parameters
max_depth = [None, 2,4,6,8,10,12]
parameters = {"max_depth": max_depth}

regressor = DecisionTreeRegressor(random_state=0)
#creating grid search cv with regressor and parameters
gs = GridSearchCV(regressor, parameters, scoring='neg_mean_squared_error')
gs.fit(X, y.values)

GridSearchCV(estimator=DecisionTreeRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [324]:
# getting best estimator and using it as regressor
regressor = gs.best_estimator_
#training the data and calculating the error
regressor.fit(X, y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))

$365,179.34


In [325]:
X

Country  EdLevel  YearsCodePro
9           4        2           4.0
11          4        0           5.0
12          2        2           6.0
16          4        0           2.0
17          0        0           6.0
...       ...      ...           ...
6531        6        2           6.0
6534        6        2           5.0
6536        2        2          35.0
6537        4        2          20.0
6538        2        0           0.5

[3179 rows x 3 columns]

In [326]:
# # country, edlevel, yearscode
# #getting a new array
X = np.array([["United States of America", 'Master’s degree',15 ]])
X

array([['United States of America', 'Master’s degree', '15']],
      dtype='<U24')

In [327]:
#to apply label encoder on country and education and take it as a float
X[:, 0] = le_country.transform(X[:,0])
X[:, 1] = le_education.transform(X[:,1])
X = X.astype(float)
X

array([[ 6.,  2., 15.]])

In [328]:
#predicting the values
y_pred = regressor.predict(X)
y_pred

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([232361.02743484])

In [329]:
#importing pickle to save our model 
import pickle
#creating a dictionary and opening a pickle file
data = {"model": regressor, "le_country": le_country, "le_education": le_education}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [330]:
#checking if data got saved in the directory
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)
#running the prediction of our loded model
regressor_loaded = data["model"]
le_country = data["le_country"]
le_education = data["le_education"]

In [331]:
y_pred = regressor_loaded.predict(X)
y_pred

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([232361.02743484])